channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cnvkit=0.9.10
  # --
  - python=3.10
  # Used by plumbum.cmd -> copier -> pipen-report
  - git
  # To make example
  - wget
  # To patch pipen-board
  - patch
  # For pipen-report
  - nodejs=18.15.0
  # For pipen-runinfo
  - time
  # tools
  - samtools
