channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cnvkit=0.9.12
  # --
  - python=3.10
  # Used by plumbum.cmd -> copier -> pipen-report
  - git
  # To make example
  - wget
  # To patch pipen-board
  - patch
  # For pipen-report
  - nodejs=20
  # For pipen-runinfo
  - time
  # tools
  - samtools
  # For convert to convert pdf to png
  - imagemagick
  - gcc_linux-64
  - pip:
    - poetry
