# Executables or binaries
[exe]
# bcftools to handle bcf/vcf files
bcftools = "bcftools"
# Control-FREEC to call cnvs
freec = "freec"
# liftover coordinates across genomes
liftover = "liftOver"
# gatk, installed via conda
gatk = "gatk"
gatk4 = "gatk"
# vdjtools, installed via conda
vdjtools = "vdjtools"
# cnvpytor
cnvpytor = "cnvpytor"
# cnvnator2VCF.pl to convert cnvpytor/cnvnator to VCF
cnvnator2vcf = "cnvnator2VCF.pl"
# wget
wget = "wget"
# aria2c
aria2c = "aria2c"
# tabix
tabix = "tabix"
# sambamba
sambamba = "sambamba"
# samtools
samtools = "samtools"
# python path where magic-impute is installed
# for scrna.ExprImpute
magic_python = "python"
# truvari
truvari = "truvari"

# Interpreters
[lang]
# Bash
bash = "bash"
# python
python = "python"
# R
rscript = "Rscript"

# Path to files/directories
[path]
# Map chain file for liftover
liftover_chain = ""
# Temporary directory
# Assign via config.py
# tmpdir = ""

[ref]
# The reference genome
reffa = ""
# The directory with reference for each chromosome
refdir = ""
# The reference sequence dictionary
refdict = ""
# The reference genes in GTF format
refgene = ""
# The reference exon in GTF format
refexon = ""
# chromosome size file
chrsize = ""
# The name of the genome assembly
genome = ""

[misc]
# Number of cores used for each job
ncores = 1

[pipeline.scrna_metabolic]
clustered = false
