# constants
"dbsnpver"       = "150"
"dbsnpver.desc"  = "The dbsnp version used in cruzdb to query SNP information."
"genome"         = "hg19"
"genome.desc"    = "Commonly used genome assembly."
"ncbikey"        = ""
"ncbikey.desc"   = "The NCBI API Key for E-Utils."
"chrorder"       = ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9",
					"chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17",
					"chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY", "chrM", "ChrMT"]
"chrorder.desc"  = "Preferrable chromsome orders, used for sorting."

# path
"affysnps"            = ""
"affysnps.desc"       = "Affymetrix SNP 6.0 Positions, used for THetA2 mostly."
"annovarDb"           = ""
"annovarDb.desc"      = "Path to database for Annovar."
"cachedir"            = "~/cache"
"cachedir.desc"       = "The directory to cache query data."
"consvdir"            = ""
"consvdir.desc"       = "The directory containing conservation scores in bigWig files.\nUse ucsc-wig2bigwig the original files are wigFix files."
"cytoband"            = ""
"cytoband.desc"       = "The cytoband file from ucsc database."
"dbsnp"               = ""
"dbsnp.desc"          = "The dbsnp common variants in VCF format."
"dbsnp_all"           = ""
"dbsnp_all.desc"      = "The dbsnp all variants in VCF format."
"exonref"             = ""
"exonref.desc"        = "Reference sequence for exons."
"gep70"               = ""
"gep70.desc"          = "The GEP70 genes (col1: 51up, col2:19down)."
"gsize"               = ""
"gsize.desc"          = "The chromsome size file."
"hlaref"              = ""
"hlaref.desc"         = "Fasta file for all HLAs with all alleles"
"highld"              = ""
"highld.desc"         = "High LD regions"
"ipidb"               = ""
"ipidb.desc"          = "The IPI xref database file."
"kallistoIdx"         = ""
"kallistoIdx.desc"    = "The kallisto index file."
iedb_mhc_i            = ""
"iedb_mhc_i.desc"     = "Path to source code directory of IEDB_MHC_I"
"lcsig"               = ""
"lcsig.desc"          = "Lung cancer gene signature (see https://www.ncbi.nlm.nih.gov/pubmed/19118056)"
"liftover"            = "liftOver"
"liftover.desc"       = "The liftover binary file."
"lochain"             = ""
"lochain.desc"        = "The liftover chain file."
"mcr"                 = ""
"mcr.desc"            = "Matlab MCR path."
"mutsig_cvrg"         = ""
"mutsig_cvrg.desc"    = "Coverage table for MutSig."
"mutsig_cvrt"         = ""
"mutsig_cvrt.desc"    = "Covariates table for MutSig."
"mutsig_mutdict"      = ""
"mutsig_mutdict.desc" = "Mutation type dictionary file for MutSig."
"mutsig_chrdir"       = ""
"mutsig_chrdir.desc"  = "Directory containing reference sequence files for MutSig."
"oncotator_db"        = ""
"oncotator_db.desc"   = "The data directory for oncotator."
"optitype"            = "OptiTypePipeline.py"
"optitype.desc"       = "Path to OptiTypePipeline.py"
"ref"                 = ""
"ref.desc"            = "The reference genome."
"refall"              = ""
"refall.desc"         = "Gene annotations downloaded from ensembl in GTF format. Coordinates were converted to 0-based, and chr was added to chromsome."
"refgene"             = ""
"refgene.desc"        = "The reference genes in GTF format."
"refexon"             = ""
"refexon.desc"        = "The exons of reference genes in GTF format."
"rsmap_gwsnp6"        = ""
"rsmap_gwsnp6.desc"   = "GenomeWideSNP_6 RSID SNP probe mapping file."
"snpeffDb"            = ""
"snpeffDb.desc"       = "Path to database for snpEff."
"superfreq_res"       = ""
"superfreq_res.desc"  = "superFreq resource directory."
"tflist"              = ""
"tflist.desc"         = "The TF list file with motif as 1st column and TF name as 2nd column."
"tfmotifs"            = ""
"tfmotifs.desc"       = "The TF motifs in MEME format."
"tmpdir"              = "/tmp/"
"tmpdir.desc"         = "The temporary directory."
"vepNonTCGAVcf"       = ""
"vepNonTCGAVcf.desc"  = "Path to ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz for VEP."
"vepDb"               = ""
"vepDb.desc"          = "Path to database for VEP."


# memoreis
"mem4G"       = "4G"
"mem4G.desc"  = "4GB memory."
"mem8G"       = "8G"
"mem8G.desc"  = "8GB memory."
"mem16G"      = "16G"
"mem16G.desc" = "16GB memory."
"mem24G"      = "24G"
"mem24G.desc" = "24GB memory."
"mem32G"      = "32G"
"mem32G.desc" = "32GB memory."

# tools
"allfit"                        = "All-FIT.py"
"allfit.desc"                   = "Path to All-FIT.py"
"annovar"                       = "annotate_variation.pl"
"annovar.desc"                  = "Path to annovar's annotate_variation.pl."
"annovar_convert"               = "convert2annovar.pl"
"annovar_convert.desc"          = "Path to annovar's convert2annovar.pl."
"art_illumina"                  = "art_illumina"
"art_illumina.desc"             = "The art_illumina program."
"awk"                           = "awk"
"awk.desc"                      = "The awk program."
"arsample"                      = "sample"
"arsample.desc"                 = "The tool `sample` by Alex Reynolds."
"bam_readcount"                 = "bam-readcount"
"bam_readcount.desc"            = "Program to generate metrics at single nucleotide positions"
"bamstats"                      = "bamstats"
"bamstats.desc"                 = "Path to bamstats."
"bamutil"                       = "bam"
"bamutil.desc"                  = "Path to bamutil."
"bbmap_repair"                  = "repair.sh"
"bbmap_repair.desc"             = "Path to repair.sh from bbmap."
"bcftools"                      = "bcftools"
"bcftools.desc"                 = "Path to bcftools."
"bedops_sort"                   = "sort-bed"
"bedops_sort.desc"              = "Path to sort-bed of bedops."
"bedtools"                      = "bedtools"
"bedtools.desc"                 = "Path to bedtools."
"biobambam_bamsort"             = "bamsort"
"biobambam_bamsort.desc"        = "Path to bamsort of biobambam."
"biobambam_bamtofastq"          = "bamtofastq"
"biobambam_bamtofastq.desc"     = "Path to bamtofastq of biobambam."
"bowtie2"                       = "bowtie2"
"bowtie2.desc"                  = "Path to bamtofastq of bowtie2."
"bwa"                           = "bwa"
"bwa.desc"                      = "Path to bamtofastq of bwa."
"bwtool"                        = "bwtool"
"bwtool.desc"                   = "Path to bwtool."
"cnvkit"                        = "cnvkit.py"
"cnvkit.desc"                   = "Path to cnvkit.py."
"cnvnator"                      = "cnvnator"
"cnvnator.desc"                 = "Path to cnvnator."
"cnvnator2vcf"                  = "cnvnator2VCF.pl"
"cnvnator2vcf.desc"             = "Path to cnvnator2VCF.pl."
"curl"                          = "curl"
"curl.desc"                     = "Path to command line tool curl."
"cutadapt"                      = "cutadapt"
"cutadapt.desc"                 = "Path to cutadapt."
"dot"                           = "dot"
"dot.desc"                      = "Path to dot."
"dtoxog"                        = "dtoxog"
"dtoxog.desc"                   = "Path to dtoxog, a wrapper of D-ToxoG."
"dwgsim"                        = "dwgsim"
"dwgsim.desc"                   = "Path to dwgsim."
"elprep"                        = "elprep"
"elprep.desc"                   = "Path to elprep."
"fastqc"                        = "fastqc"
"fastqc.desc"                   = "Path to fastqc."
"fimo"                          = "fimo"
"fimo.desc"                     = "Path to fimo from MEME suite."
"gatk"                          = "gatk"
"gatk.desc"                     = "Path to gatk."
"gatk3"                         = "gatk3"
"gatk3.desc"                    = "Path to gatk v3.8."
"gatk4"                         = "gatk"
"gatk4.desc"                    = "Path to gatk v4."
"gdc_client"                    = "gdc-client"
"gdc_client.desc"               = "The GDC client for TCGA data download."
"gistic"                        = "gistic2"
"gistic.desc"                   = "Path to gistic."
"harelba_q"                     = "x/q"
"harelba_q.desc"                = "Path to q (https://github.com/harelba/q)"
"hla_la"                        = "HLA-LA.pl"
"hla_la.desc"                   = "Path to HLA-LA.pl"
"htseq_count"                   = "htseq-count"
"htseq_count.desc"              = "Path to htseq-count."
"lichee"                        = "lichee"
"lichee.desc"                   = "Path to lichee."
"jvarkit"                       = "jvarkit"
"jvarkit.desc"                  = "Path to jvarkit."
"kallisto"                      = "kallisto"
"kallisto.desc"                 = "Path to kallisto."
"maf2vcf"                       = "maf2vcf.pl"
"maf2vcf.desc"                  = "Path to maf2vcf.pl."
"multiqc"                       = "multiqc"
"multiqc.desc"                  = "Path to multiqc."
"mutsig"                        = "mutsig"
"mutsig.desc"                   = "Path to run_MutSigCV.sh"
"netmhc"                        = "netMHC"
"netmhc.desc"                   = "Path to netMHC."
"netmhcpan"                     = "netMHCpan"
"netmhcpan.desc"                = "Path to netMHCpan."
"netmhciipan"                   = "netMHCIIpan"
"netmhciipan.desc"              = "Path to netMHCIIpan."
"netmhccons"                    = "netMHCCons"
"netmhccons.desc"               = "Path to netMHCCons."
"ngm"                           = "ngm"
"ngm.desc"                      = "Path to ngm."
"oncotator"                     = "oncotator"
"oncotator.desc"                = "Path to oncotator."
"pvacseq"                       = "pvacseq"
"pvacseq.desc"                  = "Path to pvacseq."
"picard"                        = "picard"
"picard.desc"                   = "Path to picard."
"platypus"                      = "platypus"
"platypus.desc"                 = "Path to platypus."
"plink"                         = "plink"
"plink.desc"                    = "Executable of plink."
"pyclone"                       = "PyClone"
"pyclone.desc"                  = "Path to PyClone"
"razers3"                       = "razers3"
"razers3.desc"                  = "Path to razers3."
"sambamba"                      = "sambamba"
"sambamba.desc"                 = "Path to sambamba."
"samtools"                      = "samtools"
"samtools.desc"                 = "Path to samtools."
"schism"                        = "runSchism"
"schism.desc"                   = "Path to runSchism."
"seqkit"                        = "seqkit"
"seqkit.desc"                   = "Path to seqkit."
"skewer"                        = "skewer"
"skewer.desc"                   = "Path to skewer."
"snpeff"                        = "snpEff"
"snpeff.desc"                   = "Path to snpEff."
"snpsift"                       = "SnpSift"
"snpsift.desc"                  = "Path to SnpSift."
"snvsniffer"                    = "SNVSniffer"
"snvsniffer.desc"               = "Path to SNVSniffer."
"somaticsniper"                 = "bam-somaticsniper"
"somaticsniper.desc"            = "Path to bam-somaticsniper."
"star"                          = "STAR"
"star.desc"                     = "Path to star."
"strelka_germ"                  = "configureStrelkaGermlineWorkflow.py"
"strelka_germ.desc"             = "Path to configureStrelkaGermlineWorkflow.py."
"strelka_soma"                  = "configureStrelkaSomaticWorkflow.py"
"strelka_soma.desc"             = "Path to configureStrelkaSomaticWorkflow.py."
"tabix"                         = "tabix"
"tabix.desc"                    = "Path to tabix."
"theta2"                        = "RunTHetA.py"
"theta2.desc"                   = "Path to THetA2 executable."
"tomtom"                        = "tomtom"
"tomtom.desc"                   = "tomtom from MEME suite."
"topiary"                       = "topiary"
"topiary.desc"                  = "The path to topiary."
"trimmomatic"                   = "trimmomatic"
"trimmomatic.desc"              = "Path to trimmomatic."
"vardict"                       = "vardict"
"vardict.desc"                  = "Path to vardict."
"vcf_expression_annotator"      = "vcf-expression-annotator"
"vcf_expression_annotator.desc" = "Path to vcf-expression-annotator."
"vcf2maf"                       = "vcf2maf.pl"
"vcf2maf.desc"                  = "Path to vcf2maf.pl."
"vcfanno"                       = "vcfanno"
"vcfanno.desc"                  = "Path to vcfanno."
"vcflib_vcffilter"              = "vcffilter"
"vcflib_vcffilter.desc"         = "Path to vcflib vcffilter."
"vcfstats"                      = "vcfstats"
"vcfstats.desc"                 = "Path to vcfstats."
"vcftools"                      = "vcftools"
"vcftools.desc"                 = "Path to vcftools."
"vcftools_merge"                = "vcf-merge"
"vcftools_merge.desc"           = "Path to vcftools' vcf-merge."
"vcftools_subset"               = "vcf-subset"
"vcftools_subset.desc"          = "Path to vcftools' vcf-subset."
vcfy                            = "vcfy"
"vcfy.desc"                     = "Path to vcfy"
"vep"                           = "vep"
"vep.desc"                      = "Path to vep."
"virmid"                        = "virmid"
"virmid.desc"                   = "Path to virmid."
"wgsim"                         = "wgsim"
"wgsim.desc"                    = "Path to wgsim."
"wandy"                         = "Wandy"
"wandy.desc"                    = "Path to Wandy."

# langs
"python"       = "python"
"python.desc"  = "Path to python."
"python2"      = "python2"
"python2.desc" = "Path to python2."
"java"         = "java"
"java.desc"    = "Path to java."
"Rscript"      = "Rscript"
"Rscript.desc" = "Path to Rscript."
"bash"         = "bash"
"bash.desc"    = "Path to bash."
